### ISSUE TITLE
Recommendation for bucket consistency level is not strong enough

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/storagegrid-115#4]
Page: [Other best practices for StorageGRID and FabricPool](https://docs.netapp.com/us-en/storagegrid-115/fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html)

Page: [Other best practices for StorageGRID and FabricPool](https://docs.netapp.com/us-en/storagegrid-116/fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html)

Hi the docs says:
For FabricPool buckets, the recommended bucket consistency level is “read-after-new-write.” The “available” consistency level is not recommended

Using the "available" consistency level cause data corruption! Because of this the wording "not recommended" to too week.

I suggest:
Do not use the available consistency level for buckets used as FabricPool targets.

Please also change the 11.5 documentation:
https://docs.netapp.com/us-en/storagegrid-116/fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html

**Comment by netapp-lhalbert** [comment]
Hello, @siegfried-h,

We have updated the 11.5 and 11.6 doc sites to incorporate your suggestion.

Thank you for your feedback and for helping us improve our documentation.

Best regards,

Lisa Halbert
StorageGRID Information Engineering
